server:
  port: 9999



#
spring:
#  cloud:
#    loadbalancer:
#      ribbon:
#        enabled: false
  application:
    name: zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

